import {readSaved,writeSaved} from './visitor-settings.js';
import {Chess} from 'chess.js';
export class GalleryChessGame {
 snapshot(){return {version:1,mode:this.mode,pgn:this.game.pgn()};}
 restore(saved){try{if(saved?.version!==1||![1,2].includes(saved.mode)||typeof saved.pgn!=='string'||saved.pgn.length>100000)return false;const game=new Chess();game.loadPgn(saved.pgn);this.game=game;this.mode=saved.mode;this.selected='';return true;}catch{return false;}}
 constructor(){this.game=new Chess();this.mode=1;this.selected='';}
 reset(mode=this.mode){this.mode=mode;this.game.reset();this.selected='';}
 select(square){if(this.game.isGameOver()||(this.mode===1&&this.game.turn()==='b'))return;const piece=this.game.get(square);if(piece?.color===this.game.turn()){this.selected=square;return;}if(this.selected){try{this.game.move({from:this.selected,to:square,promotion:'q'});this.selected='';}catch{}}}
 computer(){if(this.mode!==1||this.game.turn()!=='b'||this.game.isGameOver())return;let best=-Infinity,chosen;const value={p:100,n:320,b:330,r:500,q:900,k:0};const score=()=>this.game.board().flat().reduce((s,p)=>s+(p?(p.color==='b'?1:-1)*value[p.type]:0),0);for(const move of this.game.moves()){this.game.move(move);let worst=Infinity;if(this.game.isCheckmate())worst=100000;else{for(const reply of this.game.moves()){this.game.move(reply);worst=Math.min(worst,this.game.isCheckmate()?-100000:score());this.game.undo();}if(worst===Infinity)worst=0;}this.game.undo();if(worst>best){best=worst;chosen=move;}}if(chosen)this.game.move(chosen);}
 undo(){this.game.undo();if(this.mode===1&&this.game.turn()==='b')this.game.undo();this.selected='';}
 state(){let board='';for(let rank=1;rank<=8;rank++)for(const file of 'abcdefgh'){const p=this.game.get(file+rank);board+=p?(p.color==='w'?p.type.toUpperCase():p.type):'.';}const turn=this.game.turn()==='w'?'White':'Black';return {board,selected:this.selected,legal:this.selected?this.game.moves({square:this.selected,verbose:true}).map(m=>m.to).join(','):'',status:this.game.isCheckmate()?`${turn} is checkmated`:this.game.isDraw()?'Draw':`${turn} to move${this.game.isCheck()?' — check':''}`,mode:this.mode===1?'1 player · You are White':'2 players · Local turns'};}
}
export function attachChess(instance){
 const chess=new GalleryChessGame();chess.restore(readSaved("serengeti-chess",null));let timer;
 const panel=document.createElement('section');panel.id='chess-controls';panel.hidden=true;panel.setAttribute('aria-label','Chess game');panel.innerHTML='<h2>Serengeti Chess</h2><p role="status" aria-live="polite"></p><div><button data-chess="one">1 player</button><button data-chess="two">2 players</button><button data-chess="new">New game</button><button data-chess="undo">Undo</button><button data-chess="leave">Leave table</button></div><small>Select a piece, then a green square. Pawns automatically promote to queens. Two players share this board locally.</small>';document.body.append(panel);
 const board=document.createElement('details');board.className='accessible-chess';board.innerHTML='<summary>Keyboard & touch board</summary><small>Arrow keys move focus. Enter selects a piece or destination.</small><div role="grid" aria-label="Chess board"></div><button type="button" class="read-board">Read board position</button>';panel.append(board);
 let focusSquare='e2';
 const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'};
 const describe=sq=>{const piece=chess.game.get(sq);return sq+' '+(piece?(piece.color==='w'?'White ':'Black ')+names[piece.type]:'empty');};
 const drawBoard=()=>{const active=document.activeElement?.dataset.square;board.querySelector('[role="grid"]').innerHTML=Array.from({length:8},(_,r)=>'<div role="row">'+Array.from({length:8},(_,f)=>{const sq='abcdefgh'[f]+(8-r);const piece=chess.game.get(sq);const legal=chess.selected&&chess.game.moves({square:chess.selected,verbose:true}).some(m=>m.to===sq);return `<div role="gridcell"><button data-square="${sq}" tabindex="${sq===focusSquare?0:-1}" aria-label="${describe(sq)}${legal?', legal destination':''}" aria-pressed="${chess.selected===sq}" class="${(r+f)%2?'dark':'light'} ${legal?'legal':''}">${piece?`<span class="piece-${piece.color}">${{p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'}[piece.type]}</span>`:'·'}<small>${sq}</small></button></div>`;}).join('')+'</div>').join('');if(active)board.querySelector(`[data-square="${active}"]`)?.focus();};
 board.addEventListener('click',e=>{const b=e.target.closest('[data-square]');if(b){focusSquare=b.dataset.square;handle({detail:focusSquare});}});
 board.addEventListener('keydown',e=>{const b=e.target.closest('[data-square]');if(!b)return;const moves={ArrowLeft:-1,ArrowRight:1,ArrowUp:-8,ArrowDown:8};if(!(e.key in moves))return;e.preventDefault();e.stopPropagation();const buttons=[...board.querySelectorAll('[data-square]')];const index=buttons.indexOf(b);const next=buttons[Math.max(0,Math.min(63,index+moves[e.key]))];b.tabIndex=-1;next.tabIndex=0;focusSquare=next.dataset.square;next.focus();});
 board.querySelector('.read-board').onclick=()=>{panel.querySelector('[role="status"]').textContent=chess.state().status+'. '+[...board.querySelectorAll('[data-square]')].filter(b=>chess.game.get(b.dataset.square)).map(b=>describe(b.dataset.square)).join('; ');};

 const sync=()=>{const state=chess.state();instance.SendMessage('Gallery chess','SetPosition',JSON.stringify(state));panel.querySelector('p').textContent=state.mode+' · '+state.status+(state.selected?' · Selected '+state.selected+'. Legal: '+state.legal:'')+' · '+(chess.game.history().at(-1)?'Last move: '+chess.game.history().at(-1):'New game');writeSaved('serengeti-chess',chess.snapshot());drawBoard();};
 const handle=e=>{const action=e.detail;if(action==='focus'||action==='leave'){panel.hidden=action==='leave';document.body.classList.toggle('chess-active',action==='focus');return;}clearTimeout(timer);if(action==='one')chess.reset(1);else if(action==='two')chess.reset(2);else if(action==='new')chess.reset();else if(action==='undo')chess.undo();else if(/^[a-h][1-8]$/.test(action))chess.select(action);sync();if(chess.mode===1&&chess.game.turn()==='b'&&!chess.game.isGameOver())timer=setTimeout(()=>{chess.computer();sync();},250);};
 panel.addEventListener('click',e=>{const action=e.target.dataset.chess;if(!action)return;if(action==='leave')instance.SendMessage('Gallery chess','Leave');else handle({detail:action});});window.addEventListener('serengeti-chess',handle);sync();if(chess.mode===1&&chess.game.turn()==='b'&&!chess.game.isGameOver())timer=setTimeout(()=>{chess.computer();sync();},250);
}
