import {readSaved,writeSaved,restoreDiscoveries} from './visitor-settings.js';
import {checkHeadset,selectVRFilm} from './vr-entry.js';
import '@phosphor-icons/web/light';
import './style.css';
import {createPortraitWelcome} from './portrait-welcome.js';
import museumWorks from './museum-collection.json';
import submittedWorks from './gallery-submissions.json';
const $=s=>document.querySelector(s);
$('#app').innerHTML=`<canvas id="world" aria-label="Interactive Serengeti Gallery. Use W A S D or arrow keys to walk, drag to look, or choose the movement controls."></canvas><div id="shade"></div>
<div id="arrival"><img id="atrium-image" src="/serengeti-gallery/assets/atrium-cinematic.webp" width="1536" height="1024" fetchpriority="high" decoding="async" alt="A monumental portrait, a lush tree, and a warmly lit cinema inside Serengeti Gallery’s Detroit atrium."><div id="portrait-stage" aria-hidden="true"><video id="portrait-welcome" muted playsinline preload="none"></video></div><button class="scene-hotspot portrait-hotspot" id="portrait-info" aria-label="Discover the living portrait"><span>Discover the portrait</span></button><button class="scene-hotspot cinema-hotspot" id="watch" aria-label="Visit the cinema"><span>Enter the cinema</span></button></div>
<header><button class="brand" id="home" aria-label="Serengeti Gallery home"><strong>SERENGETI GALLERY</strong><small>DETROIT</small></button><nav aria-label="Main navigation"><button id="explore-nav" class="active">Gallery</button><button id="cinema-nav">Cinema</button><button id="collection-nav">Collection</button></nav><div class="header-tools"><button id="vr" class="outline">Enter VR <i class="ph-light ph-goggles" aria-hidden="true"></i></button><button class="icon-button" id="search-nav" aria-label="Search the collection"><i class="ph-light ph-magnifying-glass" aria-hidden="true"></i></button><button class="icon-button" id="menu-nav" aria-label="Open menu" aria-expanded="false"><i class="ph-light ph-list" aria-hidden="true"></i></button></div></header>
<main class="hero"><h1>The Living Portrait</h1><p>A JOURNEY THROUGH TIME,<br>CULTURE AND CREATIVITY.</p><button id="portrait-next" class="round-button" aria-label="Read the portrait story"><i class="ph-light ph-caret-right" aria-hidden="true"></i></button><button class="primary" id="discover-story">Enter gallery</button></main>
<div id="progress">THE LIVING PORTRAIT &nbsp; <span id="visited">0 / 33 works discovered</span></div><div id="hint">WASD to walk · Shift to run · Space to jump · Right-drag to look · V view</div><div id="mobile-nav" role="group" aria-label="Walk and look controls"><button id="turn-left" aria-label="Look left"><i class="ph-light ph-arrow-counter-clockwise" aria-hidden="true"></i></button><button id="forward" aria-label="Move forward"><i class="ph-light ph-arrow-up" aria-hidden="true"></i></button><button id="backward" aria-label="Move backward"><i class="ph-light ph-arrow-down" aria-hidden="true"></i></button><button id="turn-right" aria-label="Look right"><i class="ph-light ph-arrow-clockwise" aria-hidden="true"></i></button></div>
<div class="visit-actions"><button id="walk-now" class="primary">Walk with the curator <i class="ph-light ph-arrow-up-right" aria-hidden="true"></i></button><button id="run-control" class="room" aria-pressed="false">Run</button><button id="jump-control" class="room">Jump</button><button id="teleport-control" class="room">Teleport</button><button id="play-piano" class="room">Jazz piano</button><button id="play-chess" class="room">Play chess</button><button id="camera-control" class="room" aria-label="Switch character or first-person view"><i class="ph-light ph-person-simple-walk" aria-hidden="true"></i><span>Camera view</span></button></div><div class="rooms"><button class="room selected" data-room="0"><span>01</span>Atrium</button><button class="room" data-room="1"><span>02</span>Collection</button><button class="room" data-room="2"><span>03</span>Cinema</button></div>
<button id="welcome-control" class="welcome-control" aria-label="Pause the portrait welcome" aria-pressed="true"><i class="ph-light ph-pause" aria-hidden="true"></i><span>Pause welcome</span></button><div class="bottom"><button id="map-nav"><i class="ph-light ph-map-trifold" aria-hidden="true"></i><span>Map</span></button><button class="sound" id="sound"><i class="ph-light ph-speaker-high" aria-hidden="true"></i><span>Sound Off</span></button></div>
<aside id="menu" class="menu-panel hidden" aria-label="Gallery menu"><div class="caption">YOUR VISIT</div><button id="enter">Explore in 3D <i class="ph-light ph-arrow-up-right" aria-hidden="true"></i></button><button id="view-nav">Change camera view <i class="ph-light ph-person-simple-walk" aria-hidden="true"></i></button><button id="story-nav">Our story <i class="ph-light ph-arrow-up-right" aria-hidden="true"></i></button><button id="account-nav">Sign in</button><button id="signup-nav">Create an account</button><button id="settings-nav">Display & accessibility</button><button id="cart-nav">Collection bag <span id="cart-count">0</span></button><p>Art. Music. People. Ideas.<br>Detroit. Forever.</p></aside>
<div id="cinema-screen"><div id="screen-surface"></div></div>
<aside class="theater-controls hidden" id="cinema" aria-label="Jazz club screenings"><div class="caption">SERENGETI / AFTER DARK</div><h2 id="screening-title">Jazz-Off Detroit</h2><p class="muted" id="film-state" role="status">Preparing the screen…</p><div class="screening-actions"><button id="play-film" aria-label="Play screening"><i class="ph-light ph-play" aria-hidden="true"></i></button><button id="pause-film" aria-label="Pause screening"><i class="ph-light ph-pause" aria-hidden="true"></i></button><button id="restart-film" aria-label="Restart screening"><i class="ph-light ph-arrow-counter-clockwise" aria-hidden="true"></i></button></div><details><summary>Screenings & streams</summary><button id="watch-jazz">Jazz-Off Detroit ↗</button><button id="watch-gallery-film">Gallery film ↗</button><form id="screening-form"><label for="screening-url">Movie or stream link</label><input id="screening-url" type="url" required placeholder="https://…"><button type="submit">Watch on the screen</button></form><p class="muted">YouTube videos and live links, MP4 movies, or HLS streams.</p><a id="screening-link" target="_blank" rel="noopener" href="https://www.youtube.com/watch?v=4euNaGauB5k">Open on YouTube ↗</a></details></aside>
<dialog id="modal" aria-label="Gallery details"><button class="close icon-button" aria-label="Close dialog"><i class="ph-light ph-x" aria-hidden="true"></i></button><div id="modal-content"></div></dialog><div class="toast hidden" role="status" id="toast"></div><div class="loading hidden" id="loading">Serengeti Gallery<small>PREPARING YOUR ARRIVAL</small></div>`;

const portraitWelcome=createPortraitWelcome();
const artworks=[
 {id:'archive',title:'The Living Portrait',subtitle:'Featured portrait · Bill Foster reference',image:'/serengeti-gallery/assets/bill-foster.png',physical:450,digital:45,description:'A journey through time, culture and creativity. An encounter with presence, memory, and the stories we carry. This portrait anchors the gallery; its illuminated halo grows as you discover the 3D space.',note:'Supplied reference image. Exhibition title and prices are prototype proposals; authorship and sale rights await gallery confirmation.'},
 {id:'rhythm',title:'Motor City / Golden Hour',subtitle:'Generative study · Serengeti Studio',image:'/serengeti-gallery/assets/rhythm.svg',physical:280,digital:28,description:'Industrial repetition becomes a landscape of warmth. A study in Detroit rhythm, weathered copper, and the late light of the savanna.',note:'Original procedural concept artwork created for this prototype. Proposed editions and prices.'},
 {id:'grass',title:'Where the Wild Returns',subtitle:'Generative study · Serengeti Studio',image:'/serengeti-gallery/assets/grass.svg',physical:320,digital:32,description:'Organic forms move through architectural silence. Ochre, ink, and olive trace a meeting between the built world and the living one.',note:'Original procedural concept artwork created for this prototype. Proposed editions and prices.'}
];
artworks.push(...museumWorks);
for(const work of submittedWorks)artworks[work.slot]=work;
const catalogWorks=artworks.map((a,i)=>({a,i})).sort((a,b)=>Number(b.a.slot!==undefined)-Number(a.a.slot!==undefined));
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bag=[];try{const saved=JSON.parse(localStorage.getItem('serengeti-bag')||'[]');bag=Array.isArray(saved)?saved.filter(x=>artworks.some(a=>a.id===x.id&&!a.displayOnly)&&['physical','digital'].includes(x.format)).slice(0,12):[];}catch{}
const encounters=new Set(restoreDiscoveries(readSaved("serengeti-discoveries",[]),artworks.length));$("#visited").textContent=`${encounters.size} / ${artworks.length} works discovered`;let returnFocus=null;
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function updateBag(){try{localStorage.setItem('serengeti-bag',JSON.stringify(bag));}catch{/* Browsers may block storage; the current bag still works. */}$('#cart-count').textContent=bag.length;}updateBag();
function modal(html){returnFocus=document.activeElement;$('#modal-content').innerHTML=html;world.stop();$('#menu').classList.add('hidden');$('#menu-nav').setAttribute('aria-expanded','false');if(!$('#modal').open)$('#modal').showModal();}
function close(){$('#home-film')?.pause();runtime?.resume();$('#modal').close();returnFocus?.focus();}
$('.close').onclick=close;$('#modal').addEventListener('close',()=>{$('#home-film')?.pause();runtime?.resume();});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))close();});
function showArt(i){const a=artworks[i];encounters.add(i);writeSaved("serengeti-discoveries",[...encounters]);$('#visited').textContent=`${encounters.size} / ${artworks.length} works discovered`;
 modal(`<div class="modal-grid"><img class="modal-art" src="${a.image}" alt="${escape(a.title)}"><div class="modal-copy"><div class="caption">THE COLLECTION / ${String(i+1).padStart(2,'0')}</div><h2>${escape(a.title)}</h2><div class="caption">${escape(a.subtitle)}</div><p>${escape(a.description)}</p>${a.displayOnly?(a.source?`<a href="${escape(a.source)}" target="_blank" rel="noopener">View museum record ↗</a>`:`<div class="caption">ON VIEW AT SERENGETI</div>`):`<label for="format" class="caption">CHOOSE YOUR EDITION</label><select id="format"><option value="physical">Physical print — $${a.physical}</option><option value="digital">Digital edition — $${a.digital}</option></select><button class="primary" id="add">Add to collection bag +</button>`}<p class="muted">${escape(a.note)}</p><button id="walk-gallery" class="outline-small">Walk through the gallery ↗</button></div></div>`);
 $('#walk-gallery').onclick=()=>{close();world.go(i<3?0:1);};
 if($('#add'))$('#add').onclick=()=>{const format=$('#format').value;if(bag.some(x=>x.id===a.id&&x.format===format)){toast('This edition is already in your bag.');return;}bag.push({id:a.id,format});updateBag();$('#add').textContent='Added to collection';toast('Added to your collection bag');};
}
function cards(list){return list.map(({a,i})=>`<button data-art="${i}"><img loading="lazy" src="${a.image}" alt="${escape(a.title)}"><h3>${escape(a.title)}</h3><small>${a.displayOnly?'Explore artwork':'Discover editions'} ↗</small></button>`).join('');}
function wireCards(){document.querySelectorAll('[data-art]').forEach(b=>b.onclick=()=>showArt(Number(b.dataset.art)));}
function collection(search=false){modal(`<div class="list-panel"><div class="caption">33 WORKS · A WORLD OF PERSPECTIVES</div><h2 class="panel-title">The collection</h2>${search?'<label class="search-field"><i class="ph-light ph-magnifying-glass" aria-hidden="true"></i><input id="collection-search" placeholder="Search by title or artist" aria-label="Search artworks"></label>':''}<p class="search-count" id="search-count">33 works on view · 7 new gallery submissions</p><div class="catalog" id="catalog">${cards(catalogWorks)}</div></div>`);wireCards();if(search){$('#collection-search').focus();$('#collection-search').oninput=e=>{const q=e.target.value.toLowerCase();const list=catalogWorks.filter(({a})=>(a.title+' '+a.subtitle).toLowerCase().includes(q));$('#catalog').innerHTML=cards(list);$('#search-count').textContent=`${list.length} ${list.length===1?"work":"works"} found`;wireCards();};}}
function map(){modal(`<div class="list-panel"><div class="caption">FIND YOUR WAY</div><h2 class="panel-title">Explore Serengeti</h2><p>Walk as the gallery curator. Use the on-screen arrows on your phone, or WASD on a keyboard. Run with Shift, jump with Space, or use the Run and Jump buttons. Choose a destination below to teleport.</p><div class="map-destinations">${[['Atrium','The living portrait, chess table & gathering space','tree'],['Exhibition halls','33 framed works across the gallery','image'],['Cinema','Jazz-club screenings, films & streams','film-strip']].map(([name,desc,icon],i)=>`<button data-destination="${i}"><i class="ph-light ph-${icon}" aria-hidden="true"></i><span><strong>${name}</strong><small>${desc}</small></span></button>`).join('')}</div></div>`);document.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{close();world.go(Number(b.dataset.destination));});}
function story(){modal(`<div class="list-panel"><div class="caption">ART. MUSIC. PEOPLE. IDEAS.</div><h2 class="panel-title">Detroit. Forever.</h2><p>Concrete holds the city’s memory. Light, planting, and rhythm let something new grow inside it.</p><p>The Living Portrait welcomes you to an expansive exhibition of 33 works, with a lush central atrium and a dedicated cinema. Every artwork is a place to pause, discover, and connect.</p><p class="caption">THE PORTRAIT’S WELCOME</p><blockquote>“Welcome to Serengeti Gallery, here in Detroit. Explore the art, enjoy the cinema, and make yourself at home.”</blockquote><button class="primary" id="begin-walk">Begin your visit ↗</button><p class="muted">Your guide is the original Circuit Suit character, with a fedora, pinstripe suit and gold circuitry. The collection includes seven gallery submissions alongside open-access museum samples. This is a local gallery prototype.</p></div>`);$('#begin-walk').onclick=()=>{close();world.go(0);};}
function cart(){modal(`<div class="list-panel"><div class="caption">YOUR PRIVATE COLLECTION</div><h2 class="panel-title">Collection bag</h2>${bag.length?bag.map((x,i)=>{const a=artworks.find(a=>a.id===x.id);return `<div class="cart-item"><span>${escape(a.title)}<br><small>${x.format} · $${a[x.format]}</small></span><button data-remove="${i}">Remove</button></div>`;}).join(''):'<p>Your collection begins with an encounter. Explore the works and choose an edition.</p>'}<div class="spec"><span>Total</span><span>$${bag.reduce((s,x)=>s+artworks.find(a=>a.id===x.id)[x.format],0)}</span></div><button class="primary" id="checkout" ${bag.length?'':'disabled'}>Continue to checkout ↗</button><p class="muted" id="checkout-status">Preview catalog. Checkout requires approved editions and secure payment credentials.</p></div>`);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{bag.splice(Number(b.dataset.remove),1);updateBag();cart();});$('#checkout').onclick=async()=>{const b=$('#checkout');b.disabled=true;if(import.meta.env.VITE_STATIC_HOST==='true'){$('#checkout-status').textContent='Online checkout is not available yet. No payment has been taken.';return;}try{const r=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:bag})});const d=await r.json();if(!r.ok)throw Error(d.error||'Checkout unavailable');location.assign(d.url);}catch(e){$('#checkout-status').textContent=e.message;b.disabled=false;}};}
let runtime=null, runtimePromise=null;
function onRoom(n){document.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('selected',Number(b.dataset.room)===n));document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));$(n===2?'#cinema-nav':'#explore-nav').classList.add('active');}
async function getWorld(){
 if(runtime)return runtime;
 if(!runtimePromise){$('#loading').classList.remove('hidden');runtimePromise=import('./unity-world.js').then(async({createUnityGallery})=>{runtime=await createUnityGallery({artworks,onArt:showArt,toast,modalOpen:()=>$('#modal').open,onRoom});return runtime;}).catch(e=>{console.error('Gallery startup failed:',e);runtimePromise=null;$('#loading').classList.add('hidden');toast('Unity could not start. Refresh to retry; the collection is still available.');throw e;});}
 return runtimePromise;
}
const world={go:n=>getWorld().then(w=>w.go(n)).catch(()=>{}),arrive:()=>getWorld().then(w=>w.arrive()).catch(()=>{}),home:()=>{runtime?.home();$('#menu').classList.add('hidden');$('#menu-nav').setAttribute('aria-expanded','false');onRoom(-1);},stop:()=>runtime?.stop(),view:()=>runtime?runtime.view():toast('Enter the gallery to change the camera view.'),enterVR:()=>prepareVR()};
$('#collection-nav').onclick=()=>collection();$('#search-nav').onclick=()=>collection(true);$('#cart-nav').onclick=cart;$('#map-nav').onclick=map;$('#story-nav').onclick=story;$('#portrait-info').onclick=()=>showArt(0);$('#discover-story').onclick=()=>world.arrive();$('#portrait-next').onclick=story;$('#home').onclick=$('#explore-nav').onclick=()=>world.home();$('#enter').onclick=()=>world.arrive();$('#watch').onclick=$('#cinema-nav').onclick=()=>world.go(2);$('#view-nav').onclick=()=>{$('#menu').classList.add('hidden');$('#menu-nav').setAttribute('aria-expanded','false');world.view();};$('#vr').onclick=()=>world.enterVR();
document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>world.go(Number(b.dataset.room)));
$('#menu-nav').onclick=()=>{const hidden=$('#menu').classList.toggle('hidden');$('#menu-nav').setAttribute('aria-expanded',String(!hidden));hidden?runtime?.resume():world.stop();};
let audioCtx=null,audioTimer=null;
$('#sound').onclick=()=>{if($('#sound span').textContent==='Sound On'){audioCtx?.suspend();clearInterval(audioTimer);$('#sound span').textContent='Sound Off';portraitWelcome.setSound(false);window.dispatchEvent(new CustomEvent('serengeti-sound',{detail:false}));return;}audioCtx??=new AudioContext();audioCtx.resume();const chords=[[146.83,174.61,220,261.63],[130.81,164.81,196,246.94],[110,146.83,174.61,220],[123.47,155.56,196,233.08]];let beat=0;function phrase(){chords[beat++%4].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;const t=audioCtx.currentTime+i*.09;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.025,t+.04);g.gain.exponentialRampToValueAtTime(.001,t+2.7);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+2.8);});}phrase();audioTimer=setInterval(phrase,2400);$('#sound span').textContent='Sound On';portraitWelcome.setSound(true);window.dispatchEvent(new CustomEvent('serengeti-sound',{detail:true}));if(document.body.classList.contains('cinema-active')){clearInterval(audioTimer);audioCtx.suspend();}};



// The reference-matching homepage stays visible until the visitor enters Unity.


window.addEventListener('serengeti-room',e=>{if(e.detail===2){clearInterval(audioTimer);audioCtx?.suspend();}});

async function prepareVR(){
 const capability=await checkHeadset();if(!capability.supported){modal('<div class="list-panel"><h2>Open Serengeti in your headset</h2><p>'+escape(capability.message)+'</p><p>VR covers the gallery and native cinema. YouTube embeds remain available in the standard browser player.</p></div>');return;}
 try{const w=await getWorld();const selected=selectVRFilm(document.querySelector('#club-movie')?.currentSrc,new URL('/serengeti-gallery/assets/serengeti-loop.mp4',location.origin).href);
 modal('<div class="list-panel"><h2>Ready for headset VR</h2><p>Use the left stick to move, the right stick to snap turn, and the trigger to select artwork or room controls. The in-headset menu includes Gallery and Cinema.</p><p>'+(selected.fallback?'The VR cinema will use the gallery’s short ambient film. YouTube cannot be shown on this native VR screen. Select a direct MP4 or WebM in the cinema for a different film.':'The selected direct video is ready for the native cinema screen.')+'</p><button class="primary" id="start-headset">Enter headset VR</button><p id="vr-status" role="status"></p></div>');
 document.querySelector('#start-headset').onclick=()=>{close();w.enterVR(selected.url);};
 }catch{toast('VR could not prepare. The collection remains available.');}
}

document.querySelector("#teleport-control").onclick=map;

if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&!matchMedia('(pointer: coarse)').matches&&!navigator.connection?.saveData){
 const loadDepth=()=>import('./arrival-depth.js').then(m=>m.createArrivalDepth()).catch(()=>{});
 if('requestIdleCallback' in window)requestIdleCallback(loadDepth,{timeout:3000});else setTimeout(loadDepth,1000);
}

$('#settings-nav').onclick=()=>{modal(`<div class="list-panel"><h2>Make yourself comfortable</h2><label for="quality-choice">3D quality</label><select id="quality-choice"><option value="auto">Automatic (lighter on touch devices)</option><option value="low">Low — save battery</option><option value="balanced">Balanced</option><option value="high">High — sharper detail</option></select><p>Applies immediately. Lower settings reduce shadows and rendering resolution.</p><label><input id="welcome-captions" type="checkbox"> Show welcome captions</label><p>Your discoveries and chess game are saved on this browser when storage is available.</p><button id="reset-discoveries" class="outline-small">Reset discoveries</button></div>`);$('#quality-choice').value=readSaved('serengeti-quality','auto');$('#quality-choice').onchange=e=>{writeSaved('serengeti-quality',e.target.value);window.dispatchEvent(new CustomEvent('serengeti-quality',{detail:e.target.value}));};$('#welcome-captions').checked=readSaved('serengeti-captions',true)!==false;$('#welcome-captions').onchange=e=>{writeSaved('serengeti-captions',e.target.checked);window.dispatchEvent(new CustomEvent('serengeti-captions',{detail:e.target.checked}));};$('#reset-discoveries').onclick=()=>{encounters.clear();writeSaved('serengeti-discoveries',[]);$('#visited').textContent=`0 / ${artworks.length} works discovered`;toast('Discoveries reset.');};};

window.addEventListener('serengeti-discovered',e=>{const i=Number(e.detail);if(Number.isInteger(i)&&i>=0&&i<artworks.length){encounters.add(i);writeSaved('serengeti-discoveries',[...encounters]);$('#visited').textContent=`${encounters.size} / ${artworks.length} works discovered`;}});

import('./auth.js').then(({attachAccounts})=>attachAccounts({modal,close,toast})).catch(()=>toast('Accounts could not load. Please refresh to retry.'));
