export function attachPiano(instance) {
 const panel=document.createElement('aside');panel.id='piano-controls';panel.hidden=true;panel.setAttribute('aria-label','Playable jazz piano');
 const names=['C','C sharp','D','D sharp','E','F','F sharp','G','G sharp','A','A sharp','B'];
 const keyboard=['a','w','s','e','d','f','t','g','y','h','u','j','k'];
 panel.innerHTML=`<div class="caption">SERENGETI · THE PIANO LOUNGE</div><h2>Take the keys</h2><p id="piano-status" role="status">Play the keys, or choose a jazz arrangement.</p><div class="piano-songs"><button data-piano="song0">Detroit After Hours</button><button data-piano="song1">Velvet Blue</button><button data-piano="song2">Riverwalk Swing</button><button data-piano="stop">Stop music</button></div><div class="piano-keyboard" role="group" aria-label="Piano keys">${Array.from({length:13},(_,i)=>`<button class="piano-key ${names[i%12].includes('sharp')?'sharp':''}" data-note="${60+i}" aria-label="Play ${names[i%12]}${i===12?'5':'4'}"><span>${names[i%12].replace(' sharp','♯')}</span><small>${keyboard[i].toUpperCase()}</small></button>`).join('')}</div><div class="piano-footer"><small><span id="piano-note" aria-live="polite"></span>Tap keys or use A–K and W E T Y U. Original built-in jazz arrangements.</small><button data-piano="leave">Leave piano</button></div>`;
 document.body.append(panel);
 const send=action=>instance.SendMessage('Gallery jazz piano','Choose',String(action));
 panel.querySelectorAll('[data-piano]').forEach(b=>b.onclick=()=>send(b.dataset.piano));
 panel.querySelectorAll('[data-note]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();send(b.dataset.note);b.classList.add('pressed');b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>b.classList.remove('pressed');b.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.repeat){e.preventDefault();send(b.dataset.note);}};});
 window.addEventListener('keydown',e=>{if(panel.hidden||document.querySelector("#modal")?.open||e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'){send('leave');return;}const i=keyboard.indexOf(e.key.toLowerCase());if(i>=0){e.preventDefault();send(60+i);panel.querySelector(`[data-note="${60+i}"]`).classList.add('pressed');}});
 window.addEventListener('keyup',e=>{const i=keyboard.indexOf(e.key.toLowerCase());if(i>=0)panel.querySelector(`[data-note="${60+i}"]`).classList.remove('pressed');});
 window.addEventListener('serengeti-piano',e=>{const action=e.detail;if(action.startsWith('note:')){const n=Number(action.slice(5));panel.querySelector('#piano-note').textContent=`Played ${names[n%12]}${Math.floor(n/12)-1}. `;}if(action==='focus'){panel.hidden=false;document.body.classList.add('piano-active');if(document.querySelector('#sound span').textContent==='Sound On')document.querySelector('#sound').click();}if(action==='leave'){panel.hidden=true;document.body.classList.remove('piano-active');}if(action.startsWith('song'))panel.querySelector('#piano-status').textContent=['Playing: Detroit After Hours','Playing: Velvet Blue','Playing: Riverwalk Swing'][Number(action.slice(4))];if(action==='stopped')panel.querySelector('#piano-status').textContent='Music stopped. The keys are yours.';});
 window.addEventListener('blur',()=>panel.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed')));
 document.addEventListener('visibilitychange',()=>{if(document.hidden)send('stop');});
 return {leave:()=>send('leave')};
}
